== Configuration du plugin

Après installation il vous suffit d'activer le plugin celui-ci ne nénessite aucune configuration

== Configuration des jeedoms distants

Une fois sur la page du plugin (en allant sur Gestion des plugins -> Communication -> Jeedom link) il vous suffit de cliquer sur "Configurer les jeedoms distants". Une fenêtre va apparaitre et vous pourrais à partir de celle-ci configurer ou ajouter des jeedom distants.

Pour ajouter un jeedom distant il suffit de donner : 

- son addresse (interne ou externe au choix) pour le joindre
- sa clef api
- indiquer si la communication est interne ou externe (c'est utilisé pour le retour d'information, du jeedom distant vers le jeedom actuel)

[IMPORTANT]
Il faut ABSOLUMENT que la configuration réseaux des 2 jeedoms soit OK sinon le plugins ne marchera

[IMPORTANT]
Il faut que le plugin soit installé sur les 2 jeedoms

Après avoir mis la configuration de votre jeedom distant il faut aller dans l'onglet équipement pour donner les équipements à transmettre au Jeedom distant. Toutes les commandes de l'équipement seront automatique crées et configurées sur le Jeedom distant

[TIP]
Attention les plugins ayant un widgets spécifique ne l'auront pas sur le Jeedom distant (plugin camera, netatmo, network...)

[IMPORTANT]
La suppression de l'équipement sur la page de configuration des jeeodm distant ne le supprime pas automatiquement sur le jeedom distant, cela est volontaire et non un bug (c'est une sécuritée)

== Les équipements jeelink

Les équipements jeelink sont automatiquement créer lors de l'ajout d'un jeedom distant, mais vous pouvez modifier leur configuration : 

- Addresse du jeedom source
- Apikey du jeedom source
- ID de l'équipement sources et des commandes

Ces 3 parametres vous permettez de changer le jeedom source, par exemple lors du remplacement d'un jeedom sans perdre les données (historique par exemple). Pour cela il vous suffit de mettre la nouvelle addresse et clef api du jeedom source et de changer les identifiants de l'équipement et des commandes (vous les trouvez dans la configuration avancée de ceux-ci en cliquant sur la roue crantée)